name: slsu_emergency_mobile
version: 0.1.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  image_picker: ^1.1.2
  geolocator: ^12.0.0
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.0.5
  path_provider: ^2.1.4
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
